### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by cflorion** [jagreenwood/swift-log-datadog#4]
Hi :)
I am trying to use this package and I'm having a 403 status code as a response.
Would you have any idea why ? 🤔

Here is my handler: 
```
var handler = DataDogLogHandler(label: $0,
                                            key: "datadogtoken",
                                            hostname: nil,
                                            region: .EU)
```

**Comment by jagreenwood** [comment]
Hi! I had experienced the same thing when I used a DataDog access token instead of a key. Try using a key and lmk if that works.

**Comment by cflorion** [comment]
Oh I see, thanks ! ;)
